[build]
<<<<<<< Updated upstream
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
PORT = "3000"
railway.toml
=======
>>>>>>> Stashed changes
builder = "RAILPACK"
buildCommand = "npm run build"
watchPatterns = ["/src/**"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
healthcheckPath = "/api/health"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
