[build]
builder = "RAILPACK"
buildCommand = "npx prisma generate && npm run build"
watchPatterns = ["/src/**"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
healthcheckPath = "/api/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
