railway.toml
builder = "RAILPACK"
buildCommand = "npm run build"
watchPatterns = ["/src/**"]
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
overlapSeconds = 0
drainingSeconds = 0
healthcheckPath = "health.claimagent.io"
preDeployCommand = ["npm run dev"]
sleepApplication = true
useLegacyStacker = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3